const NUMBER_OF_COLUMNS = 8;
const NUMBER_OF_ROWS = 7;

export const gameLevels = [
  {
    level: 1,
    board: [
      { x: 0, y: 0, kind: 1 },
      { x: 1, y: 0, kind: 1 },
      { x: 2, y: 0, kind: 1 },
      { x: 3, y: 0, kind: 1 },
      { x: 4, y: 0, kind: 1 },
      { x: 5, y: 0, kind: 1 },
      { x: 6, y: 0, kind: 1 },
      { x: 7, y: 0, kind: 1 },
      { x: 8, y: 0, kind: 1 },
      { x: 0, y: 1, kind: 0 },
      { x: 1, y: 1, kind: 0 },
      { x: 2, y: 1, kind: 0 },
      { x: 3, y: 1, kind: 1 },
      { x: 4, y: 1, kind: 1 },
      { x: 5, y: 1, kind: 1 },
      { x: 6, y: 1, kind: 0 },
      { x: 7, y: 1, kind: 0 },
      { x: 8, y: 1, kind: 0 },
    ],
  },
  {
    level: 2,
    board: [
      { x: 0, y: 0, kind: 1 },
      { x: 1, y: 0, kind: 1 },
      { x: 2, y: 0, kind: 1 },
      { x: 3, y: 0, kind: 1 },
      { x: 4, y: 0, kind: 1 },
      { x: 5, y: 0, kind: 1 },
      { x: 6, y: 0, kind: 1 },
      { x: 7, y: 0, kind: 1 },
      { x: 8, y: 0, kind: 1 },
      { x: 0, y: 1, kind: 0 },
      { x: 1, y: 1, kind: 0 },
      { x: 2, y: 1, kind: 0 },
      { x: 3, y: 1, kind: 1 },
      { x: 4, y: 1, kind: 1 },
      { x: 5, y: 1, kind: 1 },
      { x: 6, y: 1, kind: 0 },
      { x: 7, y: 1, kind: 0 },
      { x: 8, y: 1, kind: 0 },
      { x: 0, y: 2, kind: 1 },
      { x: 1, y: 2, kind: 1 },
      { x: 2, y: 2, kind: 1 },
      { x: 3, y: 2, kind: 1 },
      { x: 4, y: 2, kind: 1 },
      { x: 5, y: 2, kind: 1 },
      { x: 6, y: 2, kind: 1 },
      { x: 7, y: 2, kind: 1 },
      { x: 8, y: 2, kind: 1 },
    ],
  },
  {
    level: 3,
    board: [
      { x: 0, y: 0, kind: 1 },
      { x: 1, y: 0, kind: 1 },
      { x: 2, y: 0, kind: 1 },
      { x: 3, y: 0, kind: 1 },
      { x: 4, y: 0, kind: 1 },
      { x: 5, y: 0, kind: 1 },
      { x: 6, y: 0, kind: 1 },
      { x: 7, y: 0, kind: 1 },
      { x: 8, y: 0, kind: 1 },
      { x: 0, y: 1, kind: 0 },
      { x: 1, y: 1, kind: 0 },
      { x: 2, y: 1, kind: 0 },
      { x: 3, y: 1, kind: 1 },
      { x: 4, y: 1, kind: 1 },
      { x: 5, y: 1, kind: 1 },
      { x: 6, y: 1, kind: 0 },
      { x: 7, y: 1, kind: 0 },
      { x: 8, y: 1, kind: 0 },
      { x: 0, y: 1, kind: 0 },
      { x: 1, y: 1, kind: 0 },
      { x: 2, y: 1, kind: 0 },
      { x: 3, y: 1, kind: 0 },
      { x: 4, y: 1, kind: 0 },
      { x: 5, y: 1, kind: 0 },
      { x: 6, y: 1, kind: 0 },
      { x: 7, y: 1, kind: 0 },
      { x: 8, y: 1, kind: 0 },
    ],
  },
  {
    level: 4,
    board: [
      { x: 0, y: 0, kind: 1 },
      { x: 1, y: 0, kind: 1 },
      { x: 2, y: 0, kind: 1 },
      { x: 3, y: 0, kind: 1 },
      { x: 4, y: 0, kind: 1 },
      { x: 5, y: 0, kind: 1 },
      { x: 6, y: 0, kind: 1 },
      { x: 7, y: 0, kind: 1 },
      { x: 8, y: 0, kind: 1 },
      { x: 0, y: 1, kind: 1 },
      { x: 1, y: 1, kind: 1 },
      { x: 2, y: 1, kind: 1 },
      { x: 3, y: 1, kind: 1 },
      { x: 4, y: 1, kind: 1 },
      { x: 5, y: 1, kind: 1 },
      { x: 6, y: 1, kind: 1 },
      { x: 7, y: 1, kind: 1 },
      { x: 8, y: 1, kind: 1 },
      { x: 0, y: 2, kind: 1 },
      { x: 1, y: 2, kind: 1 },
      { x: 2, y: 2, kind: 1 },
      { x: 3, y: 2, kind: 1 },
      { x: 4, y: 2, kind: 1 },
      { x: 5, y: 2, kind: 1 },
      { x: 6, y: 2, kind: 1 },
      { x: 7, y: 2, kind: 1 },
      { x: 8, y: 2, kind: 1 },
      { x: 0, y: 3, kind: 1 },
      { x: 1, y: 3, kind: 1 },
      { x: 2, y: 3, kind: 1 },
      { x: 3, y: 3, kind: 1 },
      { x: 4, y: 3, kind: 1 },
      { x: 5, y: 3, kind: 1 },
      { x: 6, y: 3, kind: 1 },
      { x: 7, y: 3, kind: 1 },
      { x: 8, y: 3, kind: 1 },
    ],
  },
];
